builds:
- main: ./app/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
archive:
  replacements:
    darwin: macOS
    windows: windows
    386: i386
    amd64: 64-bit
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - app/app-config.json
    - app/server-config.json
changelog:
  sort: asc
  filters:
    exclude:
      - Merge
sign:
   artifacts: checksum
