builds:
- main: ./app/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - Merge
sign:
   artifacts: checksum