language: go
go:
  - "1.10.1"
go_import_path: github.com/Encrypt-S/kauri-api
install:
  - go get -t ./...
before_script:
  - go vet ./...
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test ./...
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
after_script:
  - golint ./...
addons:
  apt:
    update: true
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
