language: go
os:
  - linux
  - osx
go:
  - "go1.9"
  - "go1.10"
go_import_path: github.com/Encrypt-S/kauri-api
# disable test caching via GOCACHE=off
env:
  global:
    - GOCACHE=off
install:
  - go get ./...
before_script:
  - go vet ./...
script:
  - go test -v -cover ./...
