language: go
go:
- 1.10.1
go_import_path: github.com/Encrypt-S/kauri-api
install:
- go get -t ./...
before_script:
- go vet ./...
before_install:
- export COVERALLS_PARALLEL=false
- export GOMAXPROCS=1
- go get github.com/mattn/goveralls
script:
- go test ./...
- "$GOPATH/bin/goveralls -service=travis-ci"
after_script:
- golint ./...
addons:
  apt:
    update: true
after_success:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
service_name: travis-pro
repo_token: Rav0oSGfDM+19j7rMXIZawA/B3NsqDCAtL7c9ILBETbJV4+eioSUHQZbU7KTjHEC1nOh51kBy/HcataFKirJ6E94ra1StWikqOmY8cqijI+9yabOoI3a99jvVr5YvfMhLTVcV8steyCYYPHzss7GMwb1qaAAJ3nBQyyvp7e8u5GiYUDjcIZfcLngt1t6tiawQ2y7fx0fItcrRYC2HG4LfKqu9C//h8NraiVoK2OULQkd+H27gIF5SIk/toStWSVgSFQh7lA6farMsBM98n/wC5FZ41ulvdsK5hhucHnshOpMuoqB+P/uQHiJj1Mf4PU3esqM8zyibhsbOeJTj2kZBlALw/V8TRWIJFPPfdoVrsHcNtebLFu7a3NmB82cWkI3S5yKuzaGnRgy115VN+v7WZTj+LXVg0/3gC3jWUJvwV5zulxolFrq3V/K0Fl15TOd4fNRETGzt+M8WGeovFSJVx+nWpg7jUbqtWqOtou+hdIdhJmKpG3jK8JpEHZGMaVR3OPb9EqVpSbDpH7fJ56WFa/Qwb9MEQKZEXfTkfVyG0GvhVSWmP4GyXG76h9oT1EMTQGSJJzV3woywehxQD3faJZLvLV6w3NVev+4dT6q4KmKT86HfRYodmcYWxNNxwgxoQ94GpODbfhwnEGY2c4MmDmojRyXDIJqUndCZe31B0s=
