language: go
go:
- 1.10.1
go_import_path: github.com/Encrypt-S/kauri-api
install:
- go get -t ./...
before_script:
- go vet ./...
before_install:
- export COVERALLS_PARALLEL=false
- export GOMAXPROCS=1
- go get github.com/mattn/goveralls
script:
- go test ./...
- "$GOPATH/bin/goveralls -service=travis-ci"
after_script:
- golint ./...
addons:
  apt:
    update: true
after_success:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
env:
  global:
    secure: XukhONqoDMK/J06O8m7j+fs/3b+xRpaYwLrFizHx3EkSf/fUYIAICt3kowtInFDNE0zpQ6GFf2xgBg5q/BmR1+k2i0h1gW3u1vF5FjL9F+Yb39g+1L6nAPCu2C4JSOXHqgAdJ9hyq4rqlcC3mv6D0CIvhwWIJOgJBFgJ0C1gHlDDLNWjIo/yJWbYU3qvTE8Rx8EGW/U8ph8G+B51MPdWa+TOSCenUd2IhVnWJjv9sGGBgI707kvNn8jgMccbFUN7Lpf7ZDRi0pHRq0MWKIayGqEkpvXhI6vWBHEbqImR3Qn1lnw5/c9JoEZWlt0yzMy54N0sEg7QT3hKxWCt61H+o+q7d3UXCsdU/CXGncCe1QGFzJBMkrLp1YW12PpeO5h2OAvOu8xcHJD/VMN6elsRLxts9LNhKP+6swGG8ZFWISZyNgafzKKYL6W8JxD4a5h2cMmic96LE4WKnFsjhY8J5uvAe9kKdQmoCydLbE9Gl5CablvKgH6ZgSbDAnAFomy+c3Thj66RWP5m1tioI3Gla9W5KjeOHjc4bJWIjwZKv/wvFikwY19il2Cy4Cth+QZ3gBlwtK17mzsWQxANuL1/1Ox5W8MnIg1WkPrZr2ki+ed8qw6MKL6W84FnqKxtvdcoQhzIlMBIksj0yAnk4V9bpwR8Ury+e9BtNXLom1b837U=
