language: go
os:
  - linux
go:
  - "1.10.x"
go_import_path: github.com/Encrypt-S/kauri-api
before_install:
  - go get github.com/appleboy/gofightget
  - go get github.com/stretchr/testify/assert
install:
  - go get ./...
before_script:
  - go vet ./...
script:
  - go test -v -cover ./...
after_script:
  - golint ./...
